version: '3'
services:
  database:
    image: mongo:3.6
    ports: 
      - 27017:27017
    
  btc-bitcore:
    build: .
    image: btc-bitcore-usdt
    links:
      - database
    ports:
      - 3001:3000
      - 8432:8432
      - 19443:18443
    environment:
      - DB_HOST=database
